//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity.Core.Metadata.Edm;
    using System.Runtime.Remoting.Contexts;
    using System.Windows.Forms;
    using static System.Windows.Forms.VisualStyles.VisualStyleElement.StartPanel;

    public partial class UserTbl
    {
        RullsDbEntities context = new RullsDbEntities();
        public int ID { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Password { get; set; }
        public string Number { get; set; }
        public int Age { get; set; }
        public string Image { get; set; }
        public int City_ID_FK { get; set; }
        public int Job_ID_FK { get; set; }
        public int Rull_ID_FK { get; set; }
        public string Email { get; set; }

        public virtual CityTbl CityTbl { get; set; }
        public virtual JobTbl JobTbl { get; set; }
        public virtual RullTbl RullTbl { get; set; }
        public void addUser(string name, string family, string password, string number, int age, string image, int city_ID_FK, int job_ID_FK, int rull_ID_FK, string email)
        {
            UserTbl user = new UserTbl();
            try
            {
                user.Name = name;
                user.Family = family;
                user.Password = password;
                user.Number = number;
                user.Age = age;
                user.Image = image;
                user.City_ID_FK = city_ID_FK;
                user.Job_ID_FK = job_ID_FK;
                user.Rull_ID_FK = rull_ID_FK;
                user.Email = email;
                context.UserTbls.Add(user);
                context.SaveChanges();
                MessageBox.Show("insert contact complated", "succsess",MessageBoxButtons.OK,MessageBoxIcon.Information);

            }
            catch(Exception)
            {
                MessageBox.Show("insert contact feild", "error",MessageBoxButtons.OK,MessageBoxIcon.Error);
            }
            finally
            {
                user = null;
            }

        }
    }
}
